import { AdAccount } from '../types';
import { subDays, parseISO } from 'date-fns';

const today = new Date();

export const MOCK_ACCOUNTS: AdAccount[] = [
  {
    id: "act_100123999201",
    name: "TK Quãng Cáo 01 (Thời Trang)",
    fbStatus: "ACTIVE",
    inventoryStatus: "IN_STOCK",
    importDate: subDays(today, 2).toISOString(),
    linkedPartners: [{id: "1002348821", name: "BM 1"}, {id: "2009221192", name: "BM 2"}],
    paymentCard: "VISA 4242",
    limit: 250,
    accountType: "REGULAR",
    accountScope: "BM",
    timezone: "UTC+07:00",
    currency: "USD",
    spend: 120.5,
  },
  {
    id: "act_100123999202",
    name: "TK Quãng Cáo 02 - Dự phòng",
    fbStatus: "DISABLED",
    inventoryStatus: "IN_STOCK",
    importDate: subDays(today, 5).toISOString(),
    linkedPartners: [{id: "1002348821", name: "BM 1"}],
    limit: 50,
    accountType: "REGULAR",
    accountScope: "PERSONAL",
    timezone: "UTC+07:00",
    currency: "USD",
    spend: 50,
  },
  {
    id: "act_200123999991",
    name: "BM5 - VO 01",
    fbStatus: "ACTIVE",
    inventoryStatus: "OUT_OF_STOCK",
    importDate: subDays(today, 10).toISOString(),
    exportDate: subDays(today, 1).toISOString(),
    linkedPartners: [{id: "3391823912", name: "BM Partner"}],
    paymentCard: "MC 5555",
    limit: 1500,
    accountType: "VO",
    accountScope: "BM",
    timezone: "UTC-08:00",
    currency: "USD",
    spend: 1450.0,
  },
  {
    id: "act_300911223344",
    name: "TK Nolimit - Nhập Khẩu",
    fbStatus: "ACTIVE",
    inventoryStatus: "IN_STOCK",
    importDate: subDays(today, 1).toISOString(),
    linkedPartners: [],
    limit: -1,
    accountType: "NOLIMIT",
    accountScope: "BM",
    timezone: "UTC+00:00",
    currency: "EUR",
    spend: 0,
  },
  {
    id: "act_400911223355",
    name: "TK Cá nhân limit 50",
    fbStatus: "IN_REVIEW",
    inventoryStatus: "IN_STOCK",
    importDate: today.toISOString(),
    linkedPartners: [],
    paymentCard: "VISA 1111",
    limit: 50,
    accountType: "REGULAR",
    accountScope: "PERSONAL",
    timezone: "UTC+07:00",
    currency: "VND",
    spend: 0,
  }
];
